from os import system
from Model.Account import Account
from Controller.AccountController import AccountController

class CreateAccount(object):
    def draw_title():
        system("clear||cls")

        title = 'CREATE ACCOUNT'
        width = 30

        print('-' * width)
        print(title.center(width))
        print('-' * width)

    def show_create_account():
        CreateAccount.draw_title()

        print('1. Create account') 
        print('B. Go back')
        print('-' * 30)

        while True:
            operation = input('Please insert the number of the operation you want to execute: ').strip().lower()
            match operation:
                case '1':
                    CreateAccount.create_account_prompt()
                case 'b':
                    from View.MainMenu import MainMenu
                    main_menu = MainMenu()
                    main_menu.show_main_menu()
                case _:
                    print("Invalid operation, Please retry")


    def create_account_prompt():
        account_controller = AccountController()
        while True:
            try:
                CreateAccount.draw_title()

                title = input("Insert the Title: ")
                username = input("Insert the Username: ")
                email = input("Insert the Email: ")
                check = input("Do you want to insert an autogenerated password? [y/N]: ").strip().lower()

                if check == 'y':
                    length = input("Insert the length of the password you want to generate: ")
                    password_length = int(length)
                    if password_length > 0:
                        password = Account.password_generator(password_length)
                        break
                else:
                    password = input("Insert the Password: ")
                    break
            except ValueError:
                print('-' * 30)
                print("Please Retry")
                print('-' * 30)
        controller = AccountController()
        controller.create_account(title, username, email, password)

        from View.MainMenu import MainMenu
        main_menu = MainMenu()
        main_menu.show_main_menu()


        