from os import system
from Model.Account import Account
from Controller.AccountController import AccountController
from Controller.ViewController import ViewController

class CreateAccount(object):
    header = 'CREATE ACCOUNT'

    @classmethod 
    def show_create_account(cls):
        view_controller = ViewController()
        view_controller.draw_header(cls.header)

        print('1. Create account') 
        print('B. Go back')
        print('-' * 30)

        while True:
            operation = input('Please insert the number of the operation you want to execute: ').strip().lower()
            match operation:
                case '1':
                    CreateAccount.create_account_prompt()
                case 'b':
                    from View.MainMenu import MainMenu
                    main_menu = MainMenu()
                    main_menu.show_main_menu()
                case _:
                    print("Invalid operation, Please retry")

    @classmethod
    def create_account_prompt(cls):
        account_controller = AccountController()
        view_controller = ViewController()
        while True:
            try:
                view_controller.draw_header(cls.header)
                
                title = account_controller.control_unique_title()
                username = input("Insert the Username: ")
                email = input("Insert the Email: ")
                check = input("Do you want to insert an autogenerated password? [y/N]: ").strip().lower()

                if check == 'y':
                    length = input("Insert the length of the password you want to generate: ")
                    password_length = int(length)
                    if password_length > 0:
                        password = Account.password_generator(password_length)
                        break
                else:
                    password = input("Insert the Password: ")
                    break
            except ValueError:
                print('-' * 30)
                print("Please Retry")
                print('-' * 30)
        account_controller.create_account(title, username, email, password)

        from View.MainMenu import MainMenu
        main_menu = MainMenu()
        main_menu.show_main_menu()


        